### ISSUE TITLE
Minifront menu drop-down is shifted

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#1447]
<img width="920" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/118478e4-36bf-4f05-ab13-f04975a0cde5">

**Comment by grod220** [comment]
This is not on main, but on the current minifront bundled with the node right? It should be fixed now, but the challenge is now propagation...

**Comment by Valentine1898** [comment]
> This is not on main, but on the current minifront bundled with the node right? It should be fixed now, but the challenge is now propagation...

I have reproduced this bug on the current main

**Comment by VanishMax** [comment]
@Valentine1898 it doesn't seem like the current main. PR https://github.com/penumbra-zone/web/pull/1425 fixed it. If the updated version was deployed, the dropdown would be aligned to the right of the button + the bottom border of the button would be hidden.

**Comment by Valentine1898** [comment]
> @Valentine1898 it doesn't seem like the current main. PR #1425 fixed it. If the updated version was deployed, the dropdown would be aligned to the right of the button + the bottom border of the button would be hidden.

It's weird because I can still reproduce it. https://jam.dev/c/3d8ff1e0-025d-4328-8920-1d561aadf99e
https://jam.dev/c/3d8ff1e0-025d-4328-8920-1d561aadf99e - here is some additional context and confirmation that the current main is being used

**Comment by VanishMax** [comment]
@Valentine1898 Sorry I misunderstood the issue, was looking at the other dropdown. Fixed it in connected PR
